# PAGE METADATA
# =============
# Date fields.
#
# NOTE:
#   1. You can generate date easily on linux using '$ date --rfc-email' command.
#   2. If date field is left blank, the current time shall be used instead.
#   3. Date should ONLY comply to RFC5322 format when manually constructed:
#                    Thu, 21 Jul 2022 14:27:39 +0800
[Date]
Created   = 'Sat, 24 Dec 2022 01:43:36 +0800'
Published = 'Sat, 24 Dec 2022 01:43:36 +0800'




# Content fields.
# NOTE:
#   1. For .Title, Hestia's string processing using page variables are allowed
#      and only limited to .Titles sub-fields.
#   2. For .Keywords, Hestia's string processing using page variables are
#      allowed but strongly discouraged.
[Content]
Title = 'Getting Started Catalog'
Keywords = [
	'Getting Started Catalog',
	'Web',
	'Tech',
	'PWA',
	'WASM',
	'Software Libraries',
	'Hugo',
	'Go',
	'TinyGo',
	'Nim',
	'ZORALab',
	"ZORALab's Hestia",
]




# Description fields.
# NOTE:
#   1. Hestia's string processing using page variables are allowed.
#   2. The .Description.Pitch is at maximum 160 characters.
#   3. The .Description.Summary is at maximum of 250 characters.
#   4. All fields shall have their whitespace cleansed during the processing.
[Description]
Pitch = '''
Redirecting you to your language.
'''
Summary = '''
Please stand-by...
'''




# Redirect fields.
# NOTE:
#   1. Hestia's URL processing is allowed for .URL field.
#   2. .Delay timing sets the delay time before redirect. Setting to '0' means
#      an immediate redirect is requested.
#   3. Redirect is only available if .Enabled is set to 'true'.
#   4. Redirect.Language is to redirect the current page to its
#      language-specific page when Javascript is made available on client side
#      or fallback to default language.
[Redirect]
Delay = 0 # second
URL = ''
Enabled = false

[Redirect.Language]
Enabled = true




# Content Files' Sourcing Location
# NOTE:
#   1. To denote where are the content sources.
#   2. If you're sourcing from assets directory, prefix 'assets/'.
#   3. If you're sourcing from layouts directory, prefix 'layouts/'.
#   2. If you're sourcing from static directory, prefix 'static/'.
#   3. If you're sourcing from partial directory, prefix 'layouts/partials/'.
[Sources]
HTML = 'layouts/content/redirect/index.html'
JSON = 'layouts/content/redirect/index.json'
CSS = 'layouts/content/redirect/index.css'
JS = 'layouts/content/redirect/index.js'
LDJSON = 'layouts/content/redirect/index.hestiaLDJSON'
Contributors = '__contributors.toml'
Thumbnails = '__thumbnails.toml'
Languages = '__languages.toml'
Assets = 'layouts/content/redirect/assets.toml'
Components = 'layouts/content/redirect/components.toml'




# Data fields.
# NOTE:
#   1. List only the page-level data files. It can be in any of the following
#      formats: '.json', '.toml', or '.yaml'.
#   2. Hestia string processing is available and shall be processed prior to
#      dataset transformation.
#   3. Sequences of the .Data array dictates sequences of loading and overriding
#      (the latter shall overwrite the former for the same data fields).
#   4. The final processed dataset shall be served as main data content in
#      supported output format (e.g. index.json).
#   5. Missing data file shall be ignored.
#   6. To add more data files, simply duplicate and add more .Data array entry.
#      Example:
#                             [[data]]
#                             Filename = 'file1.json'
#
#                             [[data]]
#                             Filename = 'file2.toml'
