# CONFIGURE THESE DATA #
baseURL = "https://hestia.zoralab.com"
theme = [
	"hestiaHUGO",
]
timeout = '10m'

archetypeDir = "archetypes"
contentDir = "content"
assetDir = "assets"
dataDir = "data"
staticDir = [
	"static",
]
layoutDir = "layouts"
themesDir = "themes"
publishDir = "public"
i18nDir = "i18n"




# !!! STOP !!!    Let the following be the default for Hestia    !!! STOP !!! #
canonifyURLs = true
buildDrafts = false
buildExpired = false
buildFuture = false
cleanDestinationDir = true
disableAliases = true
disablePathToLower = false
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
metaDataFormat = "toml"
paginate = 10
summaryLength = 70
sectionPagesMenu = "sections"
pluralizeListTitles = false
ignoreFiles = []


# Hugo injected generator as first line and broke HTML spec. Therefore, Hestia
# disables it and inject using its own renderer.
disableHugoGeneratorInject = true


# AMP disallowed javascript loading. Also, Hugo injects it as second line and
# broke its HTML spec. Therefore, Hestia disables it.
disableLiveReload = true


# Disables the following as Hestia is taking over their rendering completely.
disableKinds = [ 'sitemap', '404', 'RSS', 'term', 'taxonomy', 'robotsTXT' ]
