[CSS.Variables]
"--button-display" = "inline-block"
"--button-opacity" = "1"

"--button-margin" = ".5rem 1.2rem"
"--button-padding" = "1.3rem"

"--button-border" = "2px solid var(--button-color)"
"--button-border-radius" = ".5rem"
"--button-box-shadow" = "0 .5rem 1rem var(--color-typography-400)"

"--button-color" = "var(--color-primary-600)"
"--button-color-inverted" = "var(--color-typography-100)"
"--button-color-print" = "var(--body-color-print)"
"--button-background" = "var(--body-background)"
"--button-background-print" = "var(--body-background-print)"

"--button-font-size" = "var(--body-font-size)"
"--button-font-weight" = "700"
"--button-letter-spacing" = ".1rem"
"--button-text-align" = "center"
"--button-text-decoration" = "none"
"--button-text-transform" = "uppercase"
"--button-overflow-wrap" = "break-word"
"--button-word-break" = "break-word"
"--button-line-height" = "var(--body-line-height)"

"--button-transition" = "var(--timing-rapid)"
"--button-transform-focus" = "scale(1.05)"
"--button-opacity-disabled" = ".3"
