[CSS.Variables]
"--code-margin" = "initial"
"--code-padding" = "0 .2rem"

"--code-border" = "initial"
"--code-border-radius" = ".4rem"

"--code-letter-spacing" = 0

"--code-color" = "var(--color-primary-300)"
"--code-color-print" = "var(--body-color-print)"
"--code-background" = "var(--color-contrast-50)"
"--code-background-print" = "transparent"

"--code-overflow-wrap" = "break-word"
