[CSS.Variables]
"--divider-cut-border-bottom" = "3px dashed var(--divider-cut-color)"
"--divider-cut-border-bottom-color-inverted" = "3px dashed var(--divider-cut-color-inverted)"
"--divider-cut-content" = "\"âœ€\""

"--divider-cut-font-size" = "3.5rem"

"--divider-cut-color" = "var(--color-typography-300)"
"--divider-cut-color-inverted" = "var(--color-typography-600)"
"--divider-cut-background" = "transparent"
"--divider-cut-background-inverted" = "transparent"

"--divider-cut-margin" = "2rem 0"
