[CSS.Variables]
"--form-min-width" = "initial"
"--form-width" = "initial"
"--form-max-width" = "initial"
"--form-min-height" = "initial"
"--form-height" = "initial"
"--form-max-height" = "initial"

"--form-margin" = "2rem auto"
"--form-padding" = ".5rem"

"--form-color" = "var(--body-color)"
"--form-color-inverted" = "var(--body-color-inverted)"
"--form-color-primary" = "var(--color-primary-700)"
"--form-color-primary-inverted" = "var(--color-primary-100)"
"--form-color-valid" = "var(--body-color-indicator-green)"
"--form-color-invalid" = "var(--body-color-indicator-red)"
"--form-color-focus" = "var(--body-color-indicator-yellow)"
"--form-color-print" = "var(--body-color)"
"--form-background" = "var(--body-background)"
"--form-background-inverted" = "var(--body-background-inverted)"
"--form-background-print" = "transparent"




"--form-fieldset-margin" = "1rem"
"--form-fieldset-padding" = "0"

"--form-fieldset-border" = ".1rem solid var(--form-fieldset-color)"
"--form-fieldset-border-radius" = ".4rem"

"--form-fieldset-color" = "var(--form-color-primary)"
"--form-fieldset-color-inverted" = "var(--form-color-primary-inverted)"
"--form-fieldset-background" = "transparent"
"--form-fieldset-background-inverted" = "transparent"

"--form-fieldset-timing" = "var(--timing-normal)"
"--form-fieldset-transform-focus" = "scale(1.06)"


"--form-legend-font-weight" = "700"
"--form-legend-text-transform" = "uppercase"




"--form-label-display" = "block"

"--form-label-width" = "100%"
"--form-label-height" = "initial"

"--form-label-margin" = "0 auto"
"--form-label-padding" = "0"

"--form-label-font-size" = "1.6rem"
"--form-label-font-style" = "italic"
"--form-label-font-weight" = "700"
"--form-label-text-transform" = "titlecase"

"--form-label-color" = "var(--form-color-inverted)"
"--form-label-background" = "var(--form-fieldset-color)"




"--form-field-display" = "block"
"--form-field-opacity" = "1"
"--form-field-opacity-disabled" = ".3"

"--form-field-min-width" = "5rem"
"--form-field-width" = "100%"
"--form-field-max-width" = "initial"
"--form-field-min-height" = "initial"
"--form-field-height" = "initial"
"--form-field-max-height" = "initial"

"--form-field-margin" = "0 auto"
"--form-field-padding" = "1rem"

"--form-field-border" = "1px solid transparent"
"--form-field-border-radius" = "initial"

"--form-field-font-family" = "var(--body-font-family)"
"--form-field-font-size" = "var(--body-font-size)"
"--form-field-font-style" = "normal"
"--form-field-placeholder-font-style" = "italic"
"--form-field-font-weight" = "initial"
"--form-field-text-transform" = "initial"
"--form-field-text-align" = "center"
"--form-textarea-text-align" = "justify"

"--form-field-color" = "var(--body-color)"
"--form-field-color-inverted" = "var(--body-color-inverted)"
"--form-field-placeholder-color" = "var(--color-typography-400)"
"--form-field-background" = "var(--color-primary-50)"
"--form-field-box-shadow" = "0 1rem 2rem var(--color-typography-950)"
"--form-field-box-shadow-inverted" = "0 1rem 2rem var(--color-typography-50)"




"--form-optgroup-margin" = "2rem 1rem 0"
"--form-optgroup-padding" = "0"
"--form-optgroup-font-style" = "italic"
"--form-optgroup-text-align" = "center"




"--form-option-padding" = "0"
"--form-option-font-style" = "normal"
"--form-option-text-align" = "center"
"--form-option-before-content" = "\"\""

"--form-option-color" = "var(--form-field-color)"
"--form-option-color-checked" = "var(--form-field-color-inverted)"
"--form-option-background" = "transparent"
"--form-option-background-checked" = "var(--color-primary-300)"




"--form-checking-field-size" = "1rem"
"--form-checking-field-padding-space" = "1rem"




"--form-select-field-width" = "100%"



"--form-color-field-padding" = "0"
"--form-color-field-width" = "100%"
"--form-color-field-height" = "3rem"




"--form-button-field-display" = "inline-block"
"--form-button-field-margin" = "1rem"
"--form-button-field-margin-print" = "1rem auto"

"--form-button-field-width" = "fit-content"

"--form-button-field-border" = "2px solid transparent"
"--form-button-field-border-radius" = ".5rem"
"--form-button-field-box-shadow" = "0 1rem 2rem var(--color-typography-300)"

"--form-button-field-text-transform" = "uppercase"

"--form-button-field-color" = "var(--color-typography-50)"
"--form-button-field-color-inverted" = "var(--body-color)"
"--form-button-field-background" = "var(--color-primary-800)"
"--form-button-field-background-inverted" = "var(--color-primary-100)"
