# HESTIA PWA RESOURCES AND CACHING LIST
# =====================================
# All URLs for PWA offline caching.
#
# Hestia compatible URL processing is available for this list. All URLs must be
# bounded within the base URL and PWA scope URL pathing. You need to decide what
# kind of resources to be served offline or cached during work. To fully
# implement PWA, you **MUST** assemble and support offline resources when
# network is not available.
#
# For each dataset:
#   URL     - The URL that is required for local offline caching before use.
#   Cache   - Caching policy. They can only accept the following values:
#             'cache-first'      - Default. Resource shall use the cache version
#                                  first and then perform a network update on it
#                                  in the background. The updated resource shall
#                                  be used in the next serving. Error shall be
#                                  returned if both cached resource and network
#                                  fetched resource are simultenously
#                                  unavailable.
#                                  USED FOR:
#                                    1. fastest response.
#                                    2. always available including offline.
#                                  COMPROMISE:
#                                    1. not always up-to-date. Updated resource
#                                       only seen in next serving.
#
#             'network-first'    - Opposite of 'cache-first'. Resource shall use
#                                  the latest network fetching first and then
#                                  update the cache. If network fetching fails
#                                  (e.g. offline), the local cache version is
#                                  then used. Error shall be returned if both
#                                  cached resource and network fetched resource
#                                  are simultenously unavailable.
#                                  USED FOR:
#                                    1. always up-to-date.
#                                    2. always available including offline.
#                                  COMPROMISE:
#                                    1. slower response - due to waiting for
#                                       network for updated content.
#
#             'network-only'     - Conventional network-only resource.
#                                  USED FOR:
#                                    1. always up-to-date.
#                                    2. ultra sensitive data (confidentiality)
#                                       not suitable to retain on PWA client
#                                       side.
#                                  COMPROMISE:
#                                    1. slower response - due to waiting for
#                                       network for updated content.
#                                    3. not always available - online mode only.
#
#             'cache-only'       - Only loads from resources cached after
#                                  installation.
#                                  USED FOR:
#                                    1. fastest response.
#                                    2. always available including offline.
#                                    3. no need to burden server network.
#                                  COMPROMISE:
#                                    1. not up-to-date.
#                                    2. only can be updated during each update
#                                       or fresh installation.
#
# Example:
#   [[Contents]]
#   URL = "/en"                # --means-> '/en'
#   Cache = "cache-first"
#
#   [[Contents]]
#   URL = "/zh-hans"           # --means--> '/zh-hans'
#   Cache = "cache-first"
#
#   [[Contents]]
#   URL = "image.jpg"          # --means--> 'path/to/this-page/image.jpg'
#   Cache = "cache-first"
[[Contents]]
URL = "index.html"
Cache = "network-first"

[[Contents]]
URL = "index.json"
Cache = "network-first"

[[Contents]]
URL = "thumbnails-1200x630.jpg"
Cache = "network-first"

[[Contents]]
URL = "thumbnails-1200x1200.jpg"
Cache = "network-first"

[[Contents]]
URL = "thumbnails-480x480.jpg"
Cache = "network-first"

[[Contents]]
URL = "nate-wiley-particles.svg"
Cache = "network-first"

[[Contents]]
URL = "continuously-improved-600x600.webp"
Cache = "network-first"

[[Contents]]
URL = "continuously-improved-600x600.jpg"
Cache = "network-first"

[[Contents]]
URL = "data-driven-development-600x600.webp"
Cache = "network-first"

[[Contents]]
URL = "data-driven-development-600x600.jpg"
Cache = "network-first"

[[Contents]]
URL = "decentralized-distribution-600x600.webp"
Cache = "network-first"

[[Contents]]
URL = "decentralized-distribution-600x600.jpg"
Cache = "network-first"

[[Contents]]
URL = "mitigate-supply-chain-threat-600x600.webp"
Cache = "network-first"

[[Contents]]
URL = "mitigate-supply-chain-threat-600x600.jpg"
Cache = "network-first"

[[Contents]]
URL = "open-source-freedom-600x600.webp"
Cache = "network-first"

[[Contents]]
URL = "open-source-freedom-600x600.jpg"
Cache = "network-first"

[[Contents]]
URL = "portability-maximized-600x600.webp"
Cache = "network-first"

[[Contents]]
URL = "portability-maximized-600x600.jpg"
Cache = "network-first"

[[Contents]]
URL = "go.svg"
Cache = "network-first"

[[Contents]]
URL = "hugo.svg"
Cache = "network-first"

[[Contents]]
URL = "pwa.svg"
Cache = "network-first"

[[Contents]]
URL = "rust.svg"
Cache = "network-first"

[[Contents]]
URL = "schema-org.svg"
Cache = "network-first"

[[Contents]]
URL = "wasm.svg"
Cache = "network-first"

[[Contents]]
URL = "web.svg"
Cache = "network-first"
