[Contents.0]
Name = "{{- .Titles.Page -}}"
Width = "1200"
Height = "630"
CORS = ""
Relationship = ""
Design = ""
Preload = ""
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Contents.0.Sources]]
URL = "/en/getting-started/thumbnails-1200x630.jpg"
Type = "image/jpeg"
Media = "all"

[Contents.0.Tracks.en]
URL = ""
Kind = "subtitles"
Label = "English"
Default = false




[Contents.1]
Name = "{{- .Titles.Page -}}"
Width = "1200"
Height = "1200"
CORS = ""
Relationship = ""
Design = ""
Preload = ""
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Contents.1.Sources]]
URL = "/en/getting-started/thumbnails-1200x1200.jpg"
Type = "image/jpeg"
Media = "all"

[Contents.1.Tracks.en]
URL = ""
Kind = "subtitles"
Label = "English"
Default = false




[Contents.2]
Name = "{{- .Titles.Page -}}"
Width = "480"
Height = "480"
CORS = ""
Relationship = ""
Design = ""
Preload = ""
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Contents.2.Sources]]
URL = "/en/getting-started/thumbnails-480x480.jpg"
Type = "image/jpeg"
Media = "all"

[Contents.2.Tracks.en]
URL = ""
Kind = "subtitles"
Label = "English"
Default = false
